-- SQLite Schema Overview
-- Generated by scripts/ingest_sql.py
-- This file contains the database schema with table and column comments

-- ============================================================================
-- Table: DIM_COUNTRY
-- Purpose: Stores geography metadata: 'country' (full name), 'country_code' (ISO-2), and 'region' (e.g., Western Europe).
-- ============================================================================
CREATE TABLE "DIM_COUNTRY" (
	country TEXT,        -- Full country name (e.g., "Germany", "France")
	country_code TEXT,   -- ISO-2 country code (e.g., "DE", "FR")
	region TEXT          -- Geographic region (e.g., "Western Europe")
);

-- Sample data:
-- country: "Germany", country_code: "DE", region: "Western Europe"
-- country: "France", country_code: "FR", region: "Western Europe"

-- ============================================================================
-- Table: DIM_MODEL
-- Purpose: Catalog of vehicles: 'model_id' (unique), 'model_name', 'brand' (Toyota/Lexus), 'segment' (SUV), 'powertrain' (Petrol/HEV/PHEV).
-- ============================================================================
CREATE TABLE "DIM_MODEL" (
	model_id BIGINT,     -- Unique identifier for the vehicle model
	model_name TEXT,     -- Model name (e.g., "RAV4", "Yaris")
	brand TEXT,          -- Brand name (e.g., "Toyota", "Lexus")
	segment TEXT,        -- Vehicle segment (e.g., "SUV", "Sedan")
	powertrain TEXT      -- Powertrain type (e.g., "Petrol", "HEV", "PHEV")
);

-- Sample data:
-- model_id: 100, model_name: "RAV4", brand: "Toyota", segment: "SUV", powertrain: "HEV"
-- model_id: 101, model_name: "RAV4", brand: "Toyota", segment: "SUV", powertrain: "PHEV"

-- ============================================================================
-- Table: DIM_ORDERTYPE
-- Purpose: Order classifications: 'ordertype_id' (unique), 'ordertype_name' (Private/Fleet/Demo), 'description' (B2C/B2B/Dealer demo).
-- ============================================================================
CREATE TABLE "DIM_ORDERTYPE" (
	ordertype_id BIGINT,    -- Unique identifier for order type
	ordertype_name TEXT,    -- Order type name (e.g., "Private", "Fleet", "Demo")
	description TEXT        -- Description of order type (e.g., "B2C personal purchase", "B2B company fleet")
);

-- Sample data:
-- ordertype_id: 1, ordertype_name: "Private", description: "B2C personal purchase"
-- ordertype_id: 2, ordertype_name: "Fleet", description: "B2B company fleet"

-- ============================================================================
-- Table: FACT_SALES
-- Purpose: Core fact table of sales: 'model_id' -> DIM_MODEL, 'country_code' -> DIM_COUNTRY, plus 'year', 'month', 'contracts' (units sold).
-- Grain: model × country × year × month
-- ============================================================================
CREATE TABLE "FACT_SALES" (
	model_id BIGINT,        -- Foreign key to DIM_MODEL.model_id
	country_code TEXT,      -- Foreign key to DIM_COUNTRY.country_code
	year BIGINT,            -- Sales year (e.g., 2023, 2024)
	month BIGINT,           -- Sales month (1-12)
	contracts BIGINT        -- Number of contracts/units sold
);

-- Sample data:
-- model_id: 100, country_code: "DE", year: 2023, month: 1, contracts: 77
-- model_id: 100, country_code: "DE", year: 2023, month: 2, contracts: 88

-- ============================================================================
-- Table: FACT_SALES_ORDERTYPE
-- Purpose: Sales by order type: same keys as FACT_SALES plus 'ordertype_id' -> DIM_ORDERTYPE.
-- Extends FACT_SALES with order type breakdown for channel analysis.
-- ============================================================================
CREATE TABLE "FACT_SALES_ORDERTYPE" (
	model_id BIGINT,        -- Foreign key to DIM_MODEL.model_id
	country_code TEXT,      -- Foreign key to DIM_COUNTRY.country_code
	year BIGINT,            -- Sales year (e.g., 2023, 2024)
	month BIGINT,           -- Sales month (1-12)
	contracts BIGINT,       -- Number of contracts/units sold
	ordertype_id BIGINT     -- Foreign key to DIM_ORDERTYPE.ordertype_id
);

-- Sample data:
-- model_id: 100, country_code: "DE", year: 2023, month: 1, contracts: 77, ordertype_id: 1
-- model_id: 100, country_code: "DE", year: 2023, month: 2, contracts: 88, ordertype_id: 1

-- ============================================================================
-- Table: rate_limit
-- Purpose: Rate limiting system table for tracking daily interactions per identifier.
-- ============================================================================
CREATE TABLE rate_limit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    identifier TEXT NOT NULL,
    date TEXT NOT NULL,
    interaction_count INTEGER NOT NULL DEFAULT 0,
    last_interaction_at TEXT,
    UNIQUE(identifier, date)
);

-- ============================================================================
-- Table: sqlite_sequence
-- Purpose: SQLite system table for tracking AUTOINCREMENT sequences.
-- ============================================================================
CREATE TABLE sqlite_sequence(name,seq);

-- ============================================================================
-- Relationships:
-- ============================================================================
-- FACT_SALES.model_id -> DIM_MODEL.model_id
-- FACT_SALES.country_code -> DIM_COUNTRY.country_code
-- FACT_SALES_ORDERTYPE.model_id -> DIM_MODEL.model_id
-- FACT_SALES_ORDERTYPE.country_code -> DIM_COUNTRY.country_code
-- FACT_SALES_ORDERTYPE.ordertype_id -> DIM_ORDERTYPE.ordertype_id

-- ============================================================================
-- Sample Data Examples:
-- ============================================================================
-- DIM_COUNTRY sample rows:
--   {"country": "Germany", "country_code": "DE", "region": "Western Europe"}
--   {"country": "France", "country_code": "FR", "region": "Western Europe"}
--
-- DIM_MODEL sample rows:
--   {"model_id": 100, "model_name": "RAV4", "brand": "Toyota", "segment": "SUV", "powertrain": "HEV"}
--   {"model_id": 101, "model_name": "RAV4", "brand": "Toyota", "segment": "SUV", "powertrain": "PHEV"}
--
-- DIM_ORDERTYPE sample rows:
--   {"ordertype_id": 1, "ordertype_name": "Private", "description": "B2C personal purchase"}
--   {"ordertype_id": 2, "ordertype_name": "Fleet", "description": "B2B company fleet"}
--
-- FACT_SALES sample rows:
--   {"model_id": 100, "country_code": "DE", "year": 2023, "month": 1, "contracts": 77}
--   {"model_id": 100, "country_code": "DE", "year": 2023, "month": 2, "contracts": 88}
--
-- FACT_SALES_ORDERTYPE sample rows:
--   {"model_id": 100, "country_code": "DE", "year": 2023, "month": 1, "contracts": 77, "ordertype_id": 1}
--   {"model_id": 100, "country_code": "DE", "year": 2023, "month": 2, "contracts": 88, "ordertype_id": 1}
